FROM gengjiawen/v8-build
# for tz config, see https://serverfault.com/questions/683605/docker-container-time-timezone-will-not-reflect-changes
ENV TZ=America/Los_Angeles
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR ~/v8

RUN cd ~/v8 && git checkout 7.3-lkgr \
        && build/install-build-deps-android.sh

RUN cd ~/v8 && echo "target_os = ['android']" >> ../.gclient \
        && gclient sync \
        && tools/dev/v8gen.py list -m client.v8.ports
