version: 2

defaults: &defaults
  machine: true
  working_directory: ~/project

aliases:
  - &build-docker
    name: Build Docker Image
    command: |
      docker build -t gengjiawen/v8-build .
      docker run --rm --name v8 gengjiawen/v8-build bash -c "npx envinfo"
      docker build -t gengjiawen/v8-build:android -f Dockerfile.android .
      docker run --rm --name v8-android gengjiawen/v8-build:android bash -c "npx envinfo"
      
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run: *build-docker
  deploy:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Deploy docker
          command: |
            source ~/.bashrc
            nvm i node
            node publish_docker.js

workflows:
  version: 2
  main:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
