version: 2

defaults: &defaults
  machine: true
  working_directory: ~/project

aliases:
  - &build-docker
    - run: docker build -t gengjiawen/v8-build .
    - run: docker run --rm --name v8 gengjiawen/v8-build bash -c "npx envinfo"
    - run: docker build -t gengjiawen/v8-build:android -f Dockerfile.android .
    - run: docker run --rm --name v8-android gengjiawen/v8-build:android bash -c "npx envinfo"
      
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - *build-docker
  deploy:
    <<: *defaults
    steps:
      - checkout
      - *build-docker
      - run:
          name: Deploy docker
          command: |
            source ~/.bashrc
            nvm i node
            node publish_docker.js

workflows:
  version: 2
  main:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - master
      - deploy:
          filters:
            branches:
              only: master
